version: '3.7'

services:
  redis1:
    hostname: redis1
    image: redis:4-alpine

  sentinel1:
    hostname: sentinel1
    image: redis:4-alpine
    volumes:
      - ./docker/dev/sentinel/sentinel1.conf:/etc/sentinel1.conf
    command: redis-server /etc/sentinel1.conf --sentinel

  redis2:
    hostname: redis2
    image: redis:4-alpine

  sentinel2:
    hostname: sentinel2
    image: redis:4-alpine
    volumes:
      - ./docker/dev/sentinel/sentinel2.conf:/etc/sentinel2.conf
    command: redis-server /etc/sentinel2.conf --sentinel

  redis3:
    hostname: redis3
    image: redis:4-alpine

  sentinel3:
    hostname: sentinel3
    image: redis:4-alpine
    volumes:
      - ./docker/dev/sentinel/sentinel3.conf:/etc/sentinel3.conf
    command: redis-server /etc/sentinel3.conf --sentinel

volumes:
  data-volume:

